### ISSUE TITLE
Does not find Kubernetes secrets

### ISSUE THREAD

**Issue by matkam** [honestbee/drone-kubernetes#15]
I've created secrets for KUBERNETES_SERVER, KUBERNETES_CERT, and KUBERNETES_TOKEN. But this plugin is not using them:

```
User "default" set.
WARNING: Using insecure connection to cluster
Cluster "default" set.
Context "default" created.
Switched to context "default".
Deploying to
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

I'm using Drone 0.8.4.

**Comment by matkam** [comment]
Turns out you need to specify the secrets:

```
    pipeline:
        deploy:
            image: quay.io/honestbee/drone-kubernetes
            deployment: my-deployment
            repo: myorg/myrepo
            container: my-container
            secrets: [ KUBERNETES_SERVER, KUBERNETES_CERT, KUBERNETES_TOKEN ]
            tag: ${DRONE_COMMIT_SHA:0:8}
```
