### ISSUE TITLE
Fails to deploy to different namespace

### ISSUE THREAD

**Issue by bennythomps** [honestbee/drone-kubernetes#8]
I try deploying to a non-default namespace and receive the following error in my build. Am I missing a step?

> Error from server (Forbidden): User "system:serviceaccount:myui:default" cannot get deployments.extensions in the namespace "myui". (get deployments.extensions my-ui)

**Comment by Ulexus** [comment]
This is an RBAC restriction.  The default namespace service accounts do not have permission to modify their own deployments.  You'll want to add your own service account with the permissions you need.  Something like this should do (basically, works for me):

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: myui

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: drone-deploy
  namespace: myui
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get","list","patch","update"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: drone-deploy
  namespace: myui
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: myui
roleRef:
  kind: Role
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io
```

After you create that service account (and its permissions), you get then use the values from:

```
kubectl -n myui get secrets
# Substitute XXXXX below with the correct one from the above command
kubectl -n myui get secret/drone-deploy-token-XXXXX -o yaml | egrep 'ca.crt:|token:'
```

Use these values as per the normal docs instead of the _default_ service account ones it says to get.
